### ISSUE TITLE
Use URI class for FirmwareLocation

### ISSUE THREAD

**Issue by nicorikken** [OSGP/Protocol-Adapter-OSLP#14]
URI handling is self-implemented, rather than relying on the built-in URI class in Java. Relying on built-in classes allows the software to benefit from future platform improvements and security check, whereas the self-implemented solution will not.
File: https://github.com/OSGP/Protocol-Adapter-OSLP/blob/development/osgp-adapter-protocol-oslp/src/main/java/com/alliander/osgp/adapter/protocol/oslp/device/FirmwareLocation.java

**Comment by kevinsmeets** [comment]
The firmware location is a filesytem location at this moment. Pretty soon we will change this to a separate server. This server will contain all firmware versions. When this change is implemented we will concider using a Java built-in solution, since we will be using a real URI instead on a filesystem location. Thank you for your suggestion.
